BBS.Web/Controllers/DepositController.cs
using BBS.Core.Services;
using BBS.Interfaces.Services;
using BBS.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace BBS.Web.Controllers
{
    [Authorize]
    public class DepositController : Controller
    {
        private readonly IDepositService _depositService;
        private readonly IBankAccountService _bankAccountService;
        private readonly ICurrencyService _currencyService;
        private readonly IDepositTermService _depositTermService;
        private readonly UserManager<User> _userManager;
        private readonly ITestDataInitializerService _testDataInitializerService;

        public DepositController(IDepositService depositService,
            ICurrencyService currencyService,
            IDepositTermService depositTermService,
            IBankAccountService bankAccountService,
            UserManager<User> userManager,
           ITestDataInitializerService iTestDataInitializerService)
        {
            _depositService = depositService;
            _currencyService = currencyService;
            _depositTermService = depositTermService;
            _bankAccountService = bankAccountService;
            _userManager = userManager;
            _testDataInitializerService = iTestDataInitializerService;
        }


        public async Task<IActionResult> OpenAsync(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var depositTypes = await _depositService.GetAllTypes();
            var depositType = depositTypes.FirstOrDefault(x => x.Id == id);
            ViewData["DepositTypeId"] = depositType;
            ViewData["DepositTermId"] = new SelectList(await _depositTermService.GetAllWithTerm(), "Id", "Name");
            ViewData["CurrencyId"] = new SelectList(await _currencyService.GetAll(), "Id", "Name");
            ViewData["AccountToTransferId"] = new SelectList(await _bankAccountService.GetUserAccounts(user.Id), "Id", "Name");
            ViewData["AccountForInterestId"] = new SelectList(await _bankAccountService.GetUserAccounts(user.Id), "Id", "Name");
            ViewData["InterestRate"] = new Dictionary<int, string>(depositTypes.Select(x => new KeyValuePair<int, string>(x.Id, $"{x.AnnualRate}%")));

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OpenAsync(Deposit deposit)
        {
            var user = await _userManager.GetUserAsync(User);
            deposit.Id = 0;
            var account = _bankAccountService.GetUserAccounts(user.Id).GetAwaiter().GetResult().FirstOrDefault(x => x.Id == deposit.AccountToTransferId);
            var depositTypes = await _depositService.GetAllTypes();
            try
            {
                if (ModelState.IsValid)
                {
                        await _depositService.OpenDepositAsync(deposit, user.Id, account);
                    ViewData["SuccessMessage"] = "Updated successfully";
                    return RedirectToAction("Index", "Cards");
                }
            }
            catch (NotEnoughMoneyException)
            {
                ViewData["AboutDeposit"] = "You have not enough money in deposit";
            }

            var depositsTypes = await _depositService.GetAllTypes();
            var depositType = depositsTypes.FirstOrDefault(x => x.Id == deposit.DepositTypeId);
            ViewData["DepositTypeId"] = depositType;
            ViewData["DepositTermId"] = new SelectList(await _depositTermService.GetAllWithTerm(), "Id", "Name");
            ViewData["CurrencyId"] = new SelectList(await _currencyService.GetAll(), "Id", "Name");
            ViewData["AccountToTransferId"] = new SelectList(await _bankAccountService.GetUserAccounts(user.Id), "Id", "Name");
            ViewData["AccountForInterestId"] = new SelectList(await _bankAccountService.GetUserAccounts(user.Id), "Id", "Name");
            ViewData["InterestRate"] = new Dictionary<int, string>(depositTypes.Select(x => new KeyValuePair<int, string>(x.Id, $"{x.AnnualRate}%")));
            return View("Open");
        }



        [HttpGet]
        public async Task<IActionResult> Index(string amountString, string currencyString, string termString)
        {
            var depositTypes = await _depositService.GetAllTypes();
            ViewData["CurrencyId"] = new SelectList(await _currencyService.GetAll(), "Id", "Name");
            ViewData["TermId"] = new SelectList(await _depositTermService.GetAllWithTerm(), "Id", "Name");
            ViewData["AmountFilter"] = amountString;
            ViewData["CurrencyFilter"] = currencyString;
            ViewData["TermFilter"] = termString;

            bool isCurrencyInt = int.TryParse(currencyString, out int searchCurrency);
            bool isTermInt = int.TryParse(termString, out int searchTerm);

            if (decimal.TryParse(amountString, out decimal searchAmount) || isCurrencyInt || isTermInt)
            {
                var depositTypes2 = await _depositService.GetWithFilter(searchAmount, searchCurrency, searchTerm);

                return View(depositTypes2);
            }

            return View(depositTypes);
        }

        public async Task<IActionResult> Details(int id)
        {
            var depoType = await _depositService.GetType(id);

            if (depoType == null)
            {
                return NotFound();
            }

            return View(depoType);
        }
        public IActionResult Add()
        {
            return View();
        }
        public IActionResult DepositeManagment()
        {
            return View();
        }
    }
}

BBS.Web/Controllers/LoanController.cs
using BBS.DAL.Repositories.UnitOfWork;
using BBS.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace BBS.Web.Controllers
{
    [Authorize]
    public class LoanController : Controller
    {
        private readonly IEmploymentTypeService _IEmploymentTypeService;
        private readonly ILoanTypeService _loanService;
        private readonly ILoanTypeService _ILoanTypeService;
        private readonly ICurrencyService _ICurrencyService;
        private readonly ITestDataInitializerService ITestDataInitializerService;
        public LoanController(IEmploymentTypeService IEmploymentTypeService,
                              ILoanTypeService ILoanTypeService,
                              ICurrencyService ICurrencyService,
                              ITestDataInitializerService _ITestDataInitializerService, IUnitOfWork unitOfWork,
                               ILoanTypeService loanService)
        {
            ITestDataInitializerService = _ITestDataInitializerService;
            _ICurrencyService = ICurrencyService;
            _ILoanTypeService = ILoanTypeService;
            _IEmploymentTypeService = IEmploymentTypeService;
            _loanService = loanService;
        }
        public async Task<IActionResult> ChooseLoan()
        {

            ViewData["CurrencyId"] = new SelectList(await _ICurrencyService.GetAll(), "Id", "Name");
            var model = await _ILoanTypeService.GetLoanTypes();
            return View(model);
        }
        public async Task<IActionResult> LoanDetail(int id)
        {
            var loanType = await _ILoanTypeService.LoanTypeDetailsService(id);

            if (loanType == null)
            {
                return NotFound();
            }

            return View(loanType);
        }
        public IActionResult Add()
        {
            return View();
        }


        public IActionResult Order()
        {
            ViewData["EmploymentList"] = _IEmploymentTypeService.GetAllTypes();
            return View();
        }
    }
}

BBS.Web/Controllers/LoanRequestController.cs
using BBS.Core.CustomExceptions;
using BBS.Interfaces.Services;
using BBS.Models.Models;
using BBS.Web.Constants;
using BBS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace BBS.Web.Controllers
{
    [Authorize]
    public class LoanRequestController : Controller
    {
        private readonly IEmploymentTypeService _employmentTypeService;
        private readonly ILoanTypeService _loanTypeService;
        private readonly UserManager<User> _userManager;
        private readonly ILoanRequestService _loanRequestService;
        private readonly IBankAccountService _bankAccountService;
        private readonly IEmploymentService _employmentService;

        public LoanRequestController(IEmploymentTypeService employmentTypeService,
            ILoanTypeService loanTypeService, ICurrencyService currencyService,
            UserManager<User> userManager, ILoanRequestService loanRequestService,
            IBankAccountService bankAccountService, IEmploymentService employmentService)
        {
            _employmentTypeService = employmentTypeService;
            _loanTypeService = loanTypeService;
            _userManager = userManager;
            _loanRequestService = loanRequestService;
            _bankAccountService = bankAccountService;
            _employmentService = employmentService;
        }

        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            ViewData[ViewDataKeys.UserAccountId] = new SelectList(await _bankAccountService.GetUserAccounts(user.Id), "Id", "Name");
            ViewData[ViewDataKeys.LoanType] = await _loanTypeService.GetLoanType((int)id);
            ViewData[ViewDataKeys.EmploymentTypeId] = new SelectList(_employmentTypeService.GetAllTypes(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, EmploymentLoanRequestViewModel employmentLoanRequest)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var loanType = await _loanTypeService.GetLoanType(id);

            try
            {
                if (ModelState.IsValid)
                {
                    await _employmentService.CreateEmployment(employmentLoanRequest.Employment);

                    var employments = await _employmentService.GetEmployments();
                    var employmentId = employments.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                    await _loanRequestService.CreateLoanRequest(employmentLoanRequest.LoanRequest, loanType, user.Id, employmentId);

                    ViewData[ViewDataKeys.LoanRequestSuccess] = "Loan Request Sent Successfully!";
                }
            }
            catch (LoanTermOutOfBoundException)
            {
                ViewData[ViewDataKeys.LoanTermException] = $"Loan Term must be between {loanType.MinTerm}-{loanType.MaxTerm} months";
            }
            catch (LoanSumOutOfBoundException)
            {
                ViewData[ViewDataKeys.LoanSumException] = $"Loan Sum must be between {loanType.MinLoanSum}-{loanType.MaxLoanSum} {loanType.Currency.Name}";
            }

            ViewData[ViewDataKeys.UserAccountId] = new SelectList(await _bankAccountService.GetUserAccounts(user.Id), "Id", "Name");
            ViewData[ViewDataKeys.LoanType] = await _loanTypeService.GetLoanType(1);
            ViewData[ViewDataKeys.EmploymentTypeId] = new SelectList(_employmentTypeService.GetAllTypes(), "Id", "Name");

            return View();
        }

        public async Task<IActionResult> GetAllUsersLoan()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var loanRequests = await _loanRequestService.GetAllUsersLoan(user.Id);

            return View(loanRequests);
        }
    }
}

BBS.Web/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<BBS.Models.Models.User> signInManager

<meta name="msapplication-TileImage" content="~/images/favicondirectory/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<style>
    .container {
        max-width: 1240px !important;
    }
</style>
<nav class="navbar custom-navbar fixed-top navbar-expand-lg navbar-light bg-light" role="navigation">
    <div class="container">
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            @if (signInManager.IsSignedIn(User))
            {
                @if (User.IsInRole(BBS.Web.Constants.Roles.Admin))
                {
                    <a class="navbar-brand" asp-area="Administration" asp-controller="Dashboard" asp-action="Index"><img id="ctl00_XXX" src="/images/bbs_logo_sm_2.png" style="border: 0;float: left;width: 62px;margin-right: 20px;"></a>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="Administration" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="Administration" asp-controller="DepositTypeManagment" asp-action="Index">Deposit Managment</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="Administration" asp-controller="LoanTypeManagment" asp-action="Index">Loan Managment</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="Administration" asp-controller="CustomLoan" asp-action="Index">Custom Loans</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="Administration" asp-controller="CardRequest" asp-action="Index">Card Requests</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="Administration" asp-controller="QuestionManagement" asp-action="Index">Question Managment</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown dmenu">
                            <a class="nav-link dropdown-toggle pt-2" data-toggle="dropdown">
                                <span class="mt-3"> Hello, @User.Identity.Name </span>
                                <img src="~/images/user.svg" class="profile-img img-fluid" />
                            </a>
                            <div class="dropdown-menu sm-menu">
                                <form class="dropdown-item" method="post" asp-area="" asp-controller="UserAccount" asp-action="Logout">
                                    <button type="submit" class="nav-link btn pl-0 text-dark">Log Out <i class="fas fa-sign-out-alt"></i></button>
                                </form>
                            </div>
                        </li>
                    </ul>
                }
                else
                {
                <a class="navbar-brand" asp-area="" asp-controller="Cards" asp-action="Index"><img id="ctl00_XXX" src="/images/bbs_logo_sm_2.png" style="border: 0;float: left;width: 62px;margin-right: 20px;"></a>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Payments and Transfers</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="" asp-controller="Cards" asp-action="Index">Accounts and Cards</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="" asp-controller="Deposit" asp-action="Index">Deposit</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="" asp-controller="Loan" asp-action="ChooseLoan">Loans</a>
                        </li>
                        <li class="nav-item">
                            <a is-active class="nav-link text-dark" asp-area="" asp-controller="LoanRequest" asp-action="GetAllUsersLoan">My Loan Requests</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown dmenu">
                            <a class="nav-link dropdown-toggle pt-2" data-toggle="dropdown">
                                <span class="mt-3"> Hello, @User.Identity.Name </span>
                                <img src="~/images/user.svg" class="profile-img img-fluid" />
                            </a>
                            <div class="dropdown-menu sm-menu">
                                <a is-active class="dropdown-item nav-link" asp-area="" asp-controller="UserAccount" asp-action="Update">Settings <i class="fas fa-user-cog"></i></a>
                                <form class="dropdown-item nav-link" method="post" asp-area="" asp-controller="UserAccount" asp-action="Logout">
                                    <button type="submit" class="nav-link btn pl-0 text-dark">Log Out <i class="fas fa-sign-out-alt"></i></button>
                                </form>
                            </div>
                        </li>
                    </ul>
                }
            }
            else
            {
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a is-active asp-action="FirstStepSignUp" asp-controller="UserAccount" class="nav-link">Sign Up <i class="fas fa-user-plus"></i></a>
                    </li>
                    <li class="nav-item">
                        <a is-active asp-action="Login" asp-controller="UserAccount" class="nav-link">Log In <i class="fas fa-user-lock"></i></a>
                    </li>
                </ul>
            }
        </div>
    </div>
</nav>

BBS.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<BBS.Models.Models.User> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online Banking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/circle.css" />
    <link rel="apple-touch-icon" sizes="57x57" href="~/images/favicondirectory/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/images/favicondirectory/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/images/favicondirectory/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/images/favicondirectory/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/images/favicondirectory/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/images/favicondirectory/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/images/favicondirectory/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/images/favicondirectory/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/images/favicondirectory/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/images/favicondirectory/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/favicondirectory/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/images/favicondirectory/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/images/favicondirectory/favicon-16x16.png">
    <meta name="msapplication-TileImage" content="~/images/favicondirectory/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel='icon' href='~/images/favicondirectory/favicon.ico' type='image/x-icon' />
    <link rel="manifest" href="~/images/favicondirectory/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/images/favicondirectory/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

</head>
<body>
    <header>
        @await Html.PartialAsync("_HeaderPartial")
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BBS.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BBS.Web/Views/Shared/_SortingPartial.cshtml
@model Tuple<string, string, string>
@{
	bool ascend = (ViewData["orderInfo"] as Tuple<string, bool>).Item2;
	string orderBy = (ViewData["orderInfo"] as Tuple<string, bool>).Item1;
	string headerName = Model.Item1;
	string orderName = Model.Item2?.ToString()??headerName;
	string action = Model.Item3??"index";
}

@if (orderBy == orderName)
{
	if (ascend)
	{
		<a asp-action="index" asp-route-order="@orderName" asp-route-ascend="False">@headerName <i class="fa fa-arrow-up" aria-hidden="true"></i></a>
	}
	else
	{
		<a asp-action="index" asp-route-order="@orderName" asp-route-ascend="True">@headerName <i class="fa fa-arrow-down" aria-hidden="true"></i></a>
	}
}
else
{
	<a asp-action="index" asp-route-order="@orderName" asp-route-ascend="True">@headerName</a>
}